project_id = "sznejokyotinnjzkugzc"

[functions.fetch-news]
verify_jwt = true

[functions.rewrite-article]
verify_jwt = true

[functions.generate-news-image]
verify_jwt = true

[functions.auto-generate-news]
verify_jwt = false
